"use client";
import { useState } from "react";
import Link from "next/link";
import { useSession } from "../app-provider";
import { AddReceipt } from "../shell";
import { Icon } from "../icon";
import { EmptyState, ErrorState, Loading, PageHeader, Section, Status } from "../ui";
import { PurchaseList } from "../purchase-list";
import { useResource } from "@/lib/use-resource";
import { dateTime, decimal, money } from "@/lib/format";
export function Overview() {
  const { api, profile } = useSession();
  const [period, setPeriod] = useState("this_month");
  const [currency, setCurrency] = useState(profile.currency);
  const finance = useResource(async signal => {
    const query = { period };
    const [summary, comparison, categories] = await Promise.all([api.summary(query, signal), api.comparison(query, signal), api.categories({ ...query, limit: 100 }, signal)]);
    return { summary, comparison, categories };
  }, period);
  const recent = useResource(signal => api.purchases({ limit: 5 }, signal), "recent");
  const attention = useResource(signal => api.insights({ type: "INVENTORY_EXPIRY", limit: 3 }, signal), "attention");
  const insights = useResource(signal => api.insights({ limit: 3 }, signal), "insights");
  const metrics = finance.data?.summary.currencies.find(row => row.currency === currency) ?? finance.data?.summary.currencies[0];
  const change = finance.data?.comparison.currencies.find(row => row.currency === metrics?.currency);
  const groups = finance.data?.categories.groups.filter(row => row.currency === metrics?.currency) ?? [];
  return <><PageHeader eyebrow="YOUR EVERYDAY, AT A GLANCE" title={"Hello, " + (profile.display_name?.split(" ")[0] ?? "there") + "."} description="A little clarity for the things you buy and the life you live." actions={<label className="select-label"><Icon name="calendar" size={17} /><span className="sr-only">Overview period</span><select value={period} onChange={event => setPeriod(event.target.value)}><option value="this_month">This month</option><option value="last_month">Last month</option><option value="this_week">This week</option><option value="this_year">This year</option></select></label>} />
    <div className="overview-top"><section className="spending-hero"><div className="hero-orbit" aria-hidden="true" /><div className="hero-top"><span className="eyebrow">YOUR SPENDING SNAPSHOT</span><Icon name="spark" size={22} /></div>{finance.loading ? <Loading compact /> : finance.error ? <ErrorState message={finance.error} retry={finance.refresh} /> : metrics ? <><div className="hero-amount">{money(metrics.total_spent, metrics.currency, profile.locale)}</div><div className="hero-comparison">{change?.percentage_change != null ? <><span>{change.percentage_change.startsWith("-") ? "↓" : "↑"} {decimal(change.percentage_change.replace(/^-/, ""))}%</span> compared with the previous period</> : <span>No percentage comparison available for this period</span>}</div><div className="hero-rule" /><div className="hero-facts"><div><small>Recorded purchases</small><strong>{metrics.purchase_count}</strong></div><div><small>Average purchase</small><strong>{money(metrics.average_purchase, metrics.currency, profile.locale)}</strong></div>{finance.data!.summary.currencies.length > 1 && <label><span className="sr-only">Spending currency</span><select value={metrics.currency} onChange={event => setCurrency(event.target.value)}>{finance.data!.summary.currencies.map(row => <option key={row.currency}>{row.currency}</option>)}</select></label>}</div></> : <><h2>Your picture starts<br />with one receipt.</h2><p>See what you’ve spent, without keeping it all in your head.</p><AddReceipt className="button light" /></>}</section><section className="capture-note"><span className="note-icon"><Icon name="receipt" size={30} /></span><p className="eyebrow">SMALL HABIT. BIG CLARITY.</p><h2>Keep the memory.<br /><em>Lose the paper trail.</em></h2><p>Your next useful answer could be hiding in a receipt.</p><AddReceipt className="text-button" /></section></div>
    {finance.data && <p className="data-note">Recorded purchase totals, not cash flow. {dateTime(finance.data.summary.period.start_date, profile.locale)} to {dateTime(finance.data.summary.period.end_date, profile.locale)} (end exclusive). Currencies stay separate.</p>}
    <div className="overview-columns"><Section title="Recent purchases" href="/purchases">{recent.loading ? <Loading /> : recent.error ? <ErrorState message={recent.error} retry={recent.refresh} /> : recent.data?.length ? <PurchaseList purchases={recent.data} /> : <EmptyState title="Your purchase memory starts here">Upload a receipt to find every detail again, whenever you need it.</EmptyState>}</Section><Section title="Where it went">{finance.loading ? <Loading /> : finance.error ? <ErrorState message={finance.error} retry={finance.refresh} /> : groups.length ? <div className="category-list">{groups.slice(0, 6).map((group, index) => <div className="category-row" key={group.category_id ?? "unassigned"}><div><span className={"category-dot color-" + index} /><strong>{group.category_name ?? "Unassigned"}</strong><span>{money(group.total_amount, group.currency, profile.locale)}</span></div><progress value={Number(group.share_of_known_total_percent ?? 0)} max={100} aria-label={(group.category_name ?? "Unassigned") + " share of recorded spending"} /><small>{group.share_of_known_total_percent == null ? "Share unavailable" : decimal(group.share_of_known_total_percent) + "% of recorded spending"}</small></div>)}{(groups.length > 6 || finance.data?.categories.has_more) && <p className="caption">Showing leading categories. Shares come from the full backend total.</p>}</div> : <EmptyState icon="overview" title="Room for a clearer picture">Your spending categories will appear as purchases are recorded.</EmptyState>}</Section></div>
    <div className="overview-columns equal"><Section title="A little attention" href="/inventory">{attention.loading ? <Loading compact /> : attention.error ? <ErrorState message={attention.error} retry={attention.refresh} /> : attention.data?.length ? attention.data.map(item => <Link href={"/insights/" + item.id} className="attention-row" key={item.id}><span className="soft-icon amber"><Icon name="clock" /></span><div><strong>{item.title}</strong><p>{item.summary}</p></div><Icon name="chevron" size={16} /></Link>) : <div className="quiet-state"><Icon name="leaf" /><div><strong>No current expiry alerts</strong><p>Recorded inventory insights will appear here when something needs attention.</p></div></div>}</Section><Section title="Worth knowing" href="/insights">{insights.loading ? <Loading compact /> : insights.error ? <ErrorState message={insights.error} retry={insights.refresh} /> : insights.data?.length ? insights.data.map(item => <Link className="insight-mini" href={"/insights/" + item.id} key={item.id}><Status value={item.type} /><strong>{item.title}</strong><Icon name="arrow" size={16} /></Link>) : <div className="quiet-state"><Icon name="insights" /><div><strong>Clarity grows with your history</strong><p>Insights will surface from your recorded purchases and inventory.</p></div></div>}</Section></div>
    <Link href="/assistant" className="assistant-banner"><span className="soft-icon"><Icon name="spark" /></span><span><strong>A question about your purchases?</strong><small>Ask Raseed. The details are already remembered.</small></span><span className="text-link">Let’s talk <Icon name="arrow" size={18} /></span></Link></>;
}
