import type { AppSession } from "@/components/app-provider";
import { RaseedApi } from "@/lib/client";
import type { Insight, Lot, Message, Purchase, Receipt, WalletPass } from "@/lib/types";

export const profile = { id: "alice", firebase_uid: "firebase-alice", display_name: "Alice", email: "alice@example.com", currency: "INR", timezone: "Asia/Kolkata", locale: "en-IN", created_at: "2026-09-01T00:00:00Z", updated_at: "2026-09-01T00:00:00Z" };
export const session: AppSession = { api: new RaseedApi(async () => "test-token"), profile, reload: async () => {}, logout: async () => {} };
export const purchase: Purchase = { id: "purchase-1", receipt_id: "receipt-1", merchant_id: null, category_id: null, merchant_name_raw: "Corner Shop", purchased_at: "2026-09-28T10:00:00Z", currency: "INR", grand_total: "1234.560001", subtotal: null, tax_total: null, discount_total: null, shipping_total: null, payment_status: "PAID", notes: null, payments: [], line_items: [{ id: "line-1", raw_name: "Rice", product_id: null, category_id: null, quantity: "2", unit: "kg", unit_price: null, line_total: "1234.560001" }] };
export const receipt: Receipt = { id: "receipt-1", original_filename: "receipt.png", mime_type: "image/png", file_size: 1024, status: "UPLOADED", purchase_id: null, attempt_count: 0, failure_message: null, failure_code: null, uploaded_at: "2026-09-28T10:00:00Z", created_at: "2026-09-28T10:00:00Z" };
export const lot: Lot = { id: "lot-1", item_id: "item-1", purchase_id: purchase.id, line_item_id: "line-1", name: "Rice", unit: "kg", quantity_acquired: "2", quantity_remaining: "2", acquired_at: purchase.purchased_at, version: 1, expiry: { date: "2026-10-01", source: "MODEL_ESTIMATE", provenance: "INFERRED", confidence: "0.6", status: "NOT_DUE" } };
export const insight: Insight = { id: "insight-1", type: "SPENDING_CHANGE", title: "Spending changed", summary: "Your recorded spending increased.", status: "ACTIVE", version: 3, provenance: "DERIVED", confidence: null, source_data: { amount: "1234.560001", currency: "INR" }, calculation: { threshold: "20" }, evaluated_at: purchase.purchased_at, expires_at: "2026-10-01T00:00:00Z" };
export const pass: WalletPass = { id: "pass-1", purchase_id: purchase.id, status: "FAILED", attempt_count: 3, next_attempt_at: purchase.purchased_at, last_error_code: "wallet_configuration", synced_at: null };
export const message: Message = { id: "message-1", sequence: 2, role: "ASSISTANT", status: "COMPLETED", content: "Your recorded total is INR 1234.560001.", idempotency_key: null, reply_to_id: "user-message", failure_message: null, evidence: { citations: [{ name: "Total", tool_name: "spending_summary", pointer: "/total", value: "1234.560001" }] }, tool_executions: [], created_at: purchase.purchased_at };
